
package com.valhala.herois.services.heroisservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HeroisService", targetNamespace = "http://valhala.com/herois/services/HeroisService/v1", wsdlLocation = "file:/home/brunolv/Desenv/IdeaProjects/herois-service/src/main/webapp/WEB-INF/contracts/HeroisService.wsdl")
public class HeroisService_Service
    extends Service
{

    private final static URL HEROISSERVICE_WSDL_LOCATION;
    private final static WebServiceException HEROISSERVICE_EXCEPTION;
    private final static QName HEROISSERVICE_QNAME = new QName("http://valhala.com/herois/services/HeroisService/v1", "HeroisService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/brunolv/Desenv/IdeaProjects/herois-service/src/main/webapp/WEB-INF/contracts/HeroisService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HEROISSERVICE_WSDL_LOCATION = url;
        HEROISSERVICE_EXCEPTION = e;
    }

    public HeroisService_Service() {
        super(__getWsdlLocation(), HEROISSERVICE_QNAME);
    }

    public HeroisService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HEROISSERVICE_QNAME, features);
    }

    public HeroisService_Service(URL wsdlLocation) {
        super(wsdlLocation, HEROISSERVICE_QNAME);
    }

    public HeroisService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HEROISSERVICE_QNAME, features);
    }

    public HeroisService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HeroisService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HeroisService
     */
    @WebEndpoint(name = "HeroisServiceSOAP")
    public HeroisService getHeroisServiceSOAP() {
        return super.getPort(new QName("http://valhala.com/herois/services/HeroisService/v1", "HeroisServiceSOAP"), HeroisService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HeroisService
     */
    @WebEndpoint(name = "HeroisServiceSOAP")
    public HeroisService getHeroisServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://valhala.com/herois/services/HeroisService/v1", "HeroisServiceSOAP"), HeroisService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HEROISSERVICE_EXCEPTION!= null) {
            throw HEROISSERVICE_EXCEPTION;
        }
        return HEROISSERVICE_WSDL_LOCATION;
    }

}
